### ISSUE TITLE
error with pyfiglet

### ISSUE THREAD

**Issue by ben7147** [akashblackhat/Live-location.py#1]
I've got this error:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Live-location.py/Live-location.py", line 162, in <module>
    loop()
  File "/data/data/com.termux/files/home/Live-location.py/Live-location.py", line 28, in loop
    head = pyfiglet.figlet_format("")
           ^^^^^^^^
NameError: name 'pyfiglet' is not defined

**Comment by ben7147** [comment]
I am using Termux.

**Comment by SaintMikael** [comment]
I also got this same error....

**Comment by akashblackhat** [comment]
Ok I'm trying to fix this problem ☺️

**Comment by ghost** [comment]
I have same error, has been a while dude - from March, now August. Any update, I am waiting and really liked this before. Update us, asap.

**Comment by 4Rdee** [comment]
Traceback (most recent call last):
  File "C:\Users\Asus TUF\Live-location.py\Live-location.py", line 159, in <module>
    loop()
  File "C:\Users\Asus TUF\Live-location.py\Live-location.py", line 31, in loop
    print(Fore.GREEN + """
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 11-13: character maps to <undefined>

im using windows and using gitbash, please tell me where my failure?

**Comment by ben7147** [comment]
Welcome to Termux!

Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on libera.chat

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

~ $ nh
┌──(kali㉿localhost)-[~]
└─$ git clone https://github.com/akashblackhat/Live-location.py.git
Cloning into 'Live-location.py'...
fatal: unable to access 'https://github.com/akashblackhat/Live-location.py.git/': Could not resolve host: github.com

┌──(kali㉿localhost)-[~]
└─$





+1 bug...kr idk

**Comment by akashblackhat** [comment]
@akashblackhat come instgram

**Comment by akashblackhat** [comment]
bug fixed

**Comment by glare786** [comment]
sudo dpkg --configure -a
